# Generated by Django 3.0.7 on 2020-06-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qwant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='similar_artists',
            field=models.ManyToManyField(related_name='_artist_similar_artists_+', to='qwant.Artist', verbose_name='Similar Artists'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='api_id',
            field=models.IntegerField(unique=True, verbose_name='Qwant API id'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
    ]
