# Generated by Django 3.0.7 on 2020-06-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qwant', '0002_auto_20200625_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialChar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orig', models.CharField(max_length=50, unique=True, verbose_name='Origin character')),
                ('dest', models.CharField(max_length=50, unique=True, verbose_name='Destination character')),
            ],
        ),
    ]
