# Generated by Django 3.0.7 on 2020-06-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qwant', '0003_specialchar'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='picture',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Picture'),
        ),
    ]
